apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-center-deployment
  namespace: rabbitmq
  labels:
    app: dispatch-center
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: dispatch-center
  template:
    metadata:
      labels:
        app: dispatch-center
    spec:
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: jar
        emptyDir: {}
      initContainers:
      - name: git-cloner
        image: alpine/git
        args:
        - clone
        - --single-branch
        - --
        - https://github.com/wiilog/iot-platform.git
        - /jar
        volumeMounts:
        - mountPath: /jar
          name: jar
      - name: maven
        image: maven:3.3-jdk-8
        args:
        - mvn
        - -f
        - /jar/
        - package
        volumeMounts:
        - mountPath: /jar
          name: jar
      containers:
      - name: dispatch-center
        image: openjdk:8-jdk
          command: ["java", "-jar", "/jar/output/iot-platform.jar", "dispatch-center"]
        volumeMounts:
        - name: jar
          mountPath: /jar
        env:
        - name: RABBITMQ_IP
          value: "IP"
        - name: RABBITMQ_PWD
          value: "PWD"
        - name: RABBITMQ_USER
          value: "USR"
        - name: QUEUE
          value: "QUEUE"
        - name: RABBITMQ_TOPIC_SELECTOR_KEY
          value: ".*"